### ISSUE TITLE
Error decoding some part of the packet

### ISSUE THREAD

**Issue by batool-ali** [deepfence/FlowMeter#10]
I used flowmeter with recent pcap files from CIC but I always I get this errors and no csv file created 
```
Error decoding some part of the packet:Packet decoding error: Layer type not currently supported 
Error decoding some part of the packet:Packet decoding error: Unable to decode EthernetType 3 
```

**Comment by shyam-dev** [comment]
Hello @batool-ali  — Can you provide a link to the pcap files ? Also, can you provide some more details about your use case ?

**Comment by batool-ali** [comment]
> Hello @batool-ali — Can you provide a link to the pcap files ? Also, can you provide some more details about your use case ?

I use CIC IoT 2023 dataset
[](https://www.unb.ca/cic/datasets/iotdataset-2023.html)
I try many of the pcap files in this dataset for example 
DDos ICMP Flood 
Dos HTTP flood
Recon 
And almost all the pcap files I downloaded 

I want to get statistics about the flow as features in CSV file

**Comment by noboruma** [comment]
Hello @batool-ali 
Thanks for reporting the issue
I see 4 Recon datasets - Any Recon files would do?

**Comment by noboruma** [comment]
@batool-ali I was able to repro, here is a fix:
https://github.com/deepfence/FlowMeter/pull/11

The issue was that some packets were either ipv6 or https, and we were not supporting those protocols. I have added support to both.

I have also changed the architecture of the project a bit, should see some performance improvements and also easier build instructions.
